tags:
  FOCODAMAS: ${self:custom.environmentTags.${opt:stage}}
  FOCODAPP: CODIGO_APP
  key: ""
  value: ""
stackTags:
  FOCODAMAS: ${self:custom.environmentTags.${opt:stage}}
  FOCODAPP: CODIGO_APP
  key: ""
  value: ""
