architecture: arm64
custom:
  accounts: ${file(./config/serverless/common-config.yaml):accounts}
  accountsInfo: ${file(./config/serverless/common-config.yaml):accountsInfo}
  functionsFile: ${param:functionsFile, 'cloud'}
  roles: ${file(./config/serverless/common-config.yaml):roles}
deploymentBucket:
  name: ${self:custom.deploymentBucket.${opt:stage}}
  serverSideEncryption: AES256
environment:
  API_NEGOCIO_PAGO_CREDENCIALES: ${ssm:/CRM/${self:provider.stage}/BUSINESS_PAGO/CREDENTIALS}
  API_NEGOCIO_POLIZA_CREDENCIALES: ${ssm:/CRM/${self:provider.stage}/BUSINESS_POLIZA/CREDENTIALS}
  API_NEGOCIO_RETENCION: ${ssm:/CRM/${self:provider.stage}/CREDENTIALS/API/BUSINESS_RETENCION}
  API_NEGOCIO_VIDADNCE_CREDENCIALES: ${ssm:/CRM/${self:provider.stage}/BUSINESS_VIDADNCE/CREDENTIALS}
  HOST_API_BUS_CARTA_GARANTIA: ${ssm:/CRM/${self:provider.stage}/API/BUSINESS_CARTA_GARANTIA}
  HOST_API_BUS_POL_CROSS: ${ssm:/CRM/${self:provider.stage}/HOST_FARGATE/BUSINESS_POLIZA_CROSS}
  HOST_FARG: ${ssm:/CRM/${self:provider.stage}/HOST_FARGATE/BUSINESS_POLIZA_CROSS}
  HOST_NEGOCIO_RETENCION: ${ssm:/CRM/${self:provider.stage}/API/BUSINESS_RETENCION}
  LOG_LEVEL: INFO,DEBUG,ERROR
  NEGOCIO_PAGO: nsdatapxappexi.iman.io:9444/api/v3/rest
  REGION: ${self:provider.region}
  STAGE: ${self:provider.stage}
logRetentionInDays: 30
memorySize: 512
stackTags:
  FOCODAMAS: ${self:custom.environmentTags.${opt:stage}}
  FOCODAPP: CODIGO_APP
tags:
  FOCODAMAS: ${self:custom.environmentTags.${opt:stage}}
  FOCODAPP: CODIGO_APP
tracing:
  lambda: true
versionFunctions: false
